name: Release with manage-hc-docker.sh asset

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (e.g., v0.0.0 or v0.0b00.0)'
        required: true
        default: 'v0.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
            ref: ${{ github.ref_name }}
            fetch-depth: 0

      - name: Prepare assets
        run: |
          echo "Running on branch: ${{ github.ref_name }}"

          # Define asset names with the tag
          TAG="${{ github.event.inputs.tag_name }}"
          HC_VER_PATTERN='^[0-9]+\.[0-9]+(b[0-9][0-9])?$'

          HC_TAG=${TAG%.*}
          HC_TAG=${HC_TAG#v}
          HC_TAG=${HC_TAG#V}
          # test if HC_TAG is the right format
          [[ $HC_TAG =~ $HC_VER_PATTERN ]] || exit 1

          MGR_NAME="manage-hc-docker-$TAG.sh"

          # create a manager with version in the name and file
          sed "s/^\(HC_MANAGER_VERSION=\).*$/\1$TAG/" ./docker/manage-hc-docker.sh \
            > "./docker/$MGR_NAME"

          # add version artifact
          echo "TAG=$TAG" > VERSION.txt

          # update version in HC source
          sed -i 's/\(hc_version = "\)[0-9.]\+/\1'$HC_TAG'/' ESPHamClock/version.cpp

          # create the tars and zips
          mkdir dist
          tar -czf "dist/HC-$TAG.tar.gz" --exclude=dist .
          zip -r "dist/HC-$TAG.zip" . -x "dist/*"

          # zip file for HamClock upgrades
          zip -r "dist/ESPHamClock-V$HC_TAG.zip" ESPHamClock -x "dist/*"
          zip -r "dist/hamclock-contrib-V$HC_TAG.zip" hamclock-contrib -x "dist/*"

      - name: Create Release and Upload Asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG="${{ github.event.inputs.tag_name }}"
          HC_TAG=${TAG%.*}
          HC_TAG=${HC_TAG#v}
          HC_TAG=${HC_TAG#V}

          # Grabs file from repo tree and uploads with a label
          gh release create $TAG \
            "docker/manage-hc-docker-$TAG.sh#Manage HamClock Docker Installs" \
            "debian/install-hc-rpi#Installer for RPi and other Debian distros" \
            "dist/ESPHamClock-V$HC_TAG.zip#HamClock Source Zip with version" \
            "old-versions/ESPHamClock-V3.10.zip#HamClock Source Zip for ESP devices" \
            "old-versions/ESPHamClock-V3.10.ino.bin#HamClock ino.bin for ESP devices" \
            "dist/hamclock-contrib-V$HC_TAG.zip#HamClock 3rd party contributions" \
            --title "HamClock Release: $TAG" \
            --target ${{ github.ref_name }} \
            --generate-notes
